### ISSUE TITLE
Discohook send button greyed out

### ISSUE THREAD

**Issue by fadh1l** [discohook/site#88]
New to discohook. Trying to figure out webhooks.
Followed multiple guides but the send button is greyed out.
Anyone else have the issue?

**Comment by laikrai** [comment]
I have the same issue, the workaround is to delete the last character of the webhook URL and retype it.

**Comment by ShouldBe1** [comment]
> I have the same issue, the workaround is to delete the last character of the webhook URL and retype it.

I tried that too but I still doesn't work. What should I do now?

**Comment by Schlock-Konn** [comment]
> > I have the same issue, the workaround is to delete the last character of the webhook URL and retype it.
> 
> I tried that too but I still doesn't work. What should I do now?

From the official support Discord server: 
### "I gave the website my Webhook URL, but I can't click send.
Try restarting your browser, or using private ("incognito") mode. Usually this is because of old browser cache, though it can also happen because an extension is blocking connections to Discord."

For me, it was the Privacy Badger extension that was causing the issue. Hope this helps!

**Comment by vivisrc** [comment]
Support belongs in the Discord server
